[package]
name = "rust8"
version = "0.1.0"
authors = ["alex <wendt.alexander@googlemail.com>"]

[dependencies]
log = "0.3.7"
log4rs = "0.6.2"

piston = "0.31.1"
piston2d-graphics = "0.21.1"
pistoncore-glutin_window = "0.35.0"
piston2d-opengl_graphics = "0.42.0"
