refresh_rate: 2 minutes

appenders:
  stdout:
    kind: console
    encoder:
          pattern: "{d} - {l}: {m}{n}"

  file:
    kind: file
    path: "log/rust8.log"
    encoder:
      pattern: "{d} - {l}: {m}{n}"

root:
  level: debug
  appenders:
    - stdout
    - file


